/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Automagically Detected Files To Include=====
#include <stdio.h>
#include <setjmp.h>
#include "cspec_output_header.h"
#include "cspec_output_verbose.h"
#include "cspec_output_unit.h"
#include "CException.h"


//=======MAIN=====
int main(void)
{
  CSpecOutputStruct* output = CSpec_NewOutputVerbose();
  CSpec_Run( DESCRIPTION( EmptySkipList ), output);
  CSpec_Run( DESCRIPTION( SkipListCount ), output);
  CSpec_Run( DESCRIPTION( SkipListInsert ), output);
  CSpec_Run( DESCRIPTION( SkipListContains ), output);
  CSpec_Run( DESCRIPTION( SkipListDelete ), output);

}
